CC=g++
LDFLAGS=-lpthread


th00:
	$(CC) c++threads_00.cpp -o app $(LDFLAGS)
	./app

th01:
	$(CC) c++threads_01.cpp -o app $(LDFLAGS)
	./app

th02:
	$(CC) c++threads_02.cpp -o app $(LDFLAGS)
	./app

posix00:
	$(CC) posix_threads_00.cpp -o app $(LDFLAGS)
	./app

posix01:
	$(CC) posix_threads_01.cpp -o app $(LDFLAGS)
	./app

posix02:
	$(CC) posix_threads_02.cpp -o app $(LDFLAGS)
	./app

clean:
	rm app